### ISSUE TITLE
Extra event sent on revive

### ISSUE THREAD

**Issue by danielbrauer** [mspielberg/factorio-autobuild#1]
Autobuild sends `on_built_entity` immediately after a successful call to `revive()`, even though it passes `raise_revive = true`. I understand that this is in order to try and accommodate mods which do not handle `script_raised_revive`: https://github.com/troelsbjerre/Bottleneck/issues/56

I think that sending two events is not a good approach for the following reasons:

1. It doesn't accurately signal what is happening. The entity was revived, not revived and then created. It is reasonable for other mods to assume that entity lifecycle will be logical, and not contain an impossible series of events. If a mod _intentionally_ only handles creation events (not revives), then it might respond incorrectly to your creation event. For instance, it may have responded to the entity's original creation and now is erroneously responding to its revival because you signalled it as a creation.
2. Mods which handle both events are only able to guard against double events like this if they keep track of every event they have already handled, and then ignore duplicates. This is easy for mods which are already doing this tracking, but it's a big ask for mods that weren't doing this already.
3. Most importantly, the original problem (that some mods do not respond to `script_raised_revive`) has a simple and correct fix: those mods should add handling for that event. Your solution accommodates their oversight by pushing responsibility to otherwise correctly written mods.

I would ask that you remove the extra `on_built_entity` and instead encourage mod authors to handle all events appropriate to their mod's behaviour.

**Comment by mspielberg** [comment]
I agree with your stance. Currently the most dominant of these "auto-revive" mods is Nanobots, and Nanobots (as of this writing) only raises `on_built_entity`. If you can convince him to make this shift as well I will be more than happy to consolidate on `script_raised_revive`. See nexela/nanobots#99.

**Comment by mspielberg** [comment]
I forgot to close this when I removed the raising of `on_built_entity` in v0.2.1. Now that Construction Drones uses `script_raised_revive` only, it's more common for other mods to listen for the event.
